apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
    - port: 4040
      targetPort: 4040
  selector:
    app: auth
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: "opencrvs/ocrvs-auth:{{ .Values.image.tag }}"
          name: auth
          env:
            - name: CERT_PRIVATE_KEY_PATH
              value: /secrets/private-key.pem
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CONFIG_SMS_CODE_EXPIRY_SECONDS
              value: '{{ .Values.auth.configSmsCodeExpiry}}'
            - name: CONFIG_TOKEN_EXPIRY_SECONDS
              value: '{{ .Values.auth.configTokenExpiry }}'
            - name: METRICS_URL
              value: {{ .Values.metricsUrl }}
            - name: NOTIFICATION_SERVICE_URL
              value: {{ .Values.notificationServiceUrl }}
            - name: REDIS_HOST
              value: {{ .Values.redisHost }}
            - name: USER_MANAGEMENT_URL
              value: {{ .Values.userManagementUrl}}
            - name: AUTH_PORT
              value: "4040"
            - name: COUNTRY_CONFIG_URL
              value: {{ .Values.countryconfigUrl }}
            - name: DOMAIN
              value: "opencrvs-services-dev.svc.cluster.local"
            - name: CLIENT_APP_URL    
              value: "http://client.opencrvs-services-dev.svc.cluster.local:3000"
            - name: LOGIN_URL  
              value: "http://login.opencrvs-services-dev.svc.cluster.local:3020"
          ports:
            - containerPort: 4040
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
            - mountPath: /secrets/private-key.pem
              name: private-key
              subPath: private-key.pem
          readinessProbe:
            httpGet:
              path: /ping # FIXME: not real healthz, just checking if http server is up
              port: 4040
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key
        - secret:
            secretName: private-key
          name: private-key
