apiVersion: v1
kind: Service
metadata:
  labels:
    app: config
  name: config
spec:
  ports:
    - port: 2021
      targetPort: 2021
  selector:
    app: config
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: {{ .Values.config.replicas }}
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: "opencrvs/ocrvs-config:{{ .Values.image.tag }}"
          env:
            - name: HOST
              value: 0.0.0.0
            - name: CHECK_INVALID_TOKEN
              value: "true"
            - name: PORT
              value: "2021"
            - name: AUTH_URL
              value: {{ .Values.authUrl}}
            - name: COUNTRY_CONFIG_URL_INTERNAL
              value: {{ .Values.countryconfigUrl }}
            - name: DOCUMENTS_URL
              value: {{ .Values.documentsUrl }}
            - name: FHIR_URL
              value: {{ .Values.fhirUrl }}
            - name: GATEWAY_URL
              value: {{ .Values.gatewayUrl }}
            - name: METRICS_URL
              value: {{ .Values.metricsUrl }}
            - name: MONGO_URL
              value: {{ .Values.mongoUrl }}/application-config
            - name: SEARCH_URL
              value: {{ .Values.searchUrl }}
            - name: USER_MANAGEMENT_URL
              value: {{ .Values.userManagementUrl }}
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
          ports:
            - containerPort: 2021
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key