apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhooks
  name: webhooks
spec:
  ports:
    - port: 2525
      targetPort: 2525
  selector:
    app: webhooks
  #type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhooks
  name: webhooks
spec:
  replicas: {{ .Values.webhooks.replicas }}
  selector:
    matchLabels:
      app: webhooks
  template:
    metadata:
      labels:
        app: webhooks
    spec:
      containers:
        - name: webhooks
          image: "opencrvs/ocrvs-webhooks:{{ .Values.image.tag }}"
          env:
            - name: NODE_ENV
              value: development
            - name: QA_ENV
              value: "false"
            - name: AUTH_URL
              value: {{ .Values.authUrl }}
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CERT_PRIVATE_KEY_PATH
              value: /secrets/private-key.pem
            - name: CHECK_INVALID_TOKEN
              value: "true"
            - name: FHIR_URL
              value: {{ .Values.fhirUrl }}
            - name: HOST
              value: 0.0.0.0
            - name: MONGO_URL
              value: {{ .Values.mongoUrl }}/webhooks
            - name: REDIS_HOST
              value: {{ .Values.redisHost }}
            - name: USER_MANAGEMENT_URL
              value: {{ .Values.userManagementUrl }}
          ports:
            - containerPort: 2525
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
            - mountPath: /secrets/private-key.pem
              name: private-key
              subPath: private-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key
        - secret:
            secretName: private-key
          name: private-key