# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Scan files for vulnerabilities

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  security-scan-development:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: 'ghcr.io/opencrvs/trivy-db'
          TRIVY_JAVA_DB_REPOSITORY: 'ghcr.io/opencrvs/trivy-java-db'
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

  security-scan-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: 'base'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'branch'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: 'ghcr.io/opencrvs/trivy-db'
          TRIVY_JAVA_DB_REPOSITORY: 'ghcr.io/opencrvs/trivy-java-db'
        with:
          scan-type: 'fs'
          scan-ref: 'base'
          trivy-config: ./base/trivy.yaml
          format: 'sarif'
          output: './trivy-results-base.sarif'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: 'ghcr.io/opencrvs/trivy-db'
          TRIVY_JAVA_DB_REPOSITORY: 'ghcr.io/opencrvs/trivy-java-db'
        with:
          scan-type: 'fs'
          scan-ref: 'branch'
          trivy-config: ./branch/trivy.yaml
          format: 'sarif'
          output: './trivy-results-branch.sarif'

      - name: Remove lines that are always expected to be different
        run: |
          sed -i '/"uri": "file:\/\/\/github\/workspace\/base\//d' ${{ github.workspace }}/trivy-results-base.sarif
          sed -i '/"uri": "file:\/\/\/github\/workspace\/branch\//d' ${{ github.workspace }}/trivy-results-branch.sarif

      - name: Diff Trivy results
        run: diff -u ./trivy-results-base.sarif ./trivy-results-branch.sarif
